### ISSUE TITLE
gnuastro, conda and apple silicon

### ISSUE THREAD

**Issue by lboogaard** [conda-forge/gnuastro-feedstock#24]
### Comment:

Currently, `gnuastro` is not installable via `conda` for apple silicon architecture (M1/M2). It does however appear to compile without errors (just tested on an M2 MacBook Pro).

Would you be interested in making `gnuastro` available via `conda` for this architecture as well?

**Comment by sebastian-luna-valero** [comment]
Hi,

Would you be willing to help us with it? ;) 

Best regards,
Sebastian

**Comment by lboogaard** [comment]
Yes I would be happy to help - I do need some pointers where to start, because I have not done this before.

My first assumption is that in the actual build recipe nothing fundamental needs to be changed. It's mainly making that recipe available for the new architecture.

**Comment by mohammad-akhlaghi** [comment]
I just saw that it was merged into the main branch :clap:!

Thanks a lot @lboogaard for bringing this up and to @sebastian-luna-valero for the prompt help in implementing it :+1: .

Thanks to you, people on more CPU architectures can enjoy Gnuastro. Thank you :smiley:.

**Comment by mohammad-akhlaghi** [comment]
I saw that the binary files for osx-arm64 are already in Anaconda and ready for usage :smiley: : https://anaconda.org/conda-forge/gnuastro/files

@lboogaard, it would be great if you can try it on your system and if it works correctly, you can close this issue :wink:.

**Comment by lboogaard** [comment]
It works!
