### ISSUE TITLE
Buildling (not publishing) alpha-releases

### ISSUE THREAD

**Issue by mohammad-akhlaghi** [conda-forge/gnuastro-feedstock#28]
### Comment:

Gnuastro [0.19.109 was released](https://lists.gnu.org/archive/html/info-gnuastro/2023-04/msg00000.html) a few days ago as an alpha-release for version 0.20.

It would be great if we can configure Conda to test-build these alpha-releases also so we can catch bugs early (and not be confronted with a crash in a Conda architecture after an official release; as happened in [0.16.1 release](https://lists.gnu.org/archive/html/info-gnuastro/2021-10/msg00001.html)). 

Of course, since it is an alpha-release, we don't want to be ultimately published in Conda; we just want it to be built on all the Conda architectures to see if there are problems. 

The Gnuastro alpha releases are published with this base-URL: https://alpha.gnu.org/gnu/gnuastro

@sebastian-luna-valero, do you know if this is possible in Conda?

**Comment by sebastian-luna-valero** [comment]
Hi!

It's apparently possible, but I haven't tried this before myself:

https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

Would you like to give it a go?

Thanks!

**Comment by mohammad-akhlaghi** [comment]
That does indeed sound like a good solution :+1: .

Unfortunately I don't have much experience with the Conda environment development to do it fast myself. Do you think it is something you can do without putting much energy?

**Comment by mohammad-akhlaghi** [comment]
I  think I found a nice hack: I manually updated the version and hash, and pushed a separate branch and a fake pull request #29.  Afterwards, Github's actions automatically started building on that commit and in a few minutes, I was able to confirm that the confirm that the check is successful on all Conda environments we test.

Having confirmed a successful build, I just closed that branch, and will wait for the automatic one to come :wink:.

**Comment by sebastian-luna-valero** [comment]
sorry I couldn't work on this before the release; happy to offer my help with this; could you please ping me via this issue for the next alpha-release and we'll see how it goes?

**Comment by mohammad-akhlaghi** [comment]
Thanks to the nice checklist provided by @sebastian-luna-valero in #35, I was able to add a fully tested checklist in the Gnuastro release checklist to simplify the process in future releases :smile:. The relevant commits in Gnuastro's source are below:

- [d251642077](https://git.savannah.gnu.org/cgit/gnuastro.git/commit/?id=d25164207707): `doc/release-checklist.txt`: adding steps for conda
- [428b76204b](https://git.savannah.gnu.org/cgit/gnuastro.git/commit/?id=428b76204b): `developer-build`: new option to specify compression
- [46f9616085](https://git.savannah.gnu.org/cgit/gnuastro.git/commit/?id=46f961608580): `doc/release-checklist.txt`: improved/edited conda-forge instructions

This issue can now be closed.
