### ISSUE TITLE
include astquery functionality on conda

### ISSUE THREAD

**Issue by jmoldon** [conda-forge/gnuastro-feedstock#6]
Hi @mohammad-akhlaghi, would it be possible to have a new release for gnuastro version 0.13.95-56609, so `astquery` is also included in the most recent conda package?

Thanks

**Comment by mohammad-akhlaghi** [comment]
Thanks a lot for raising this point Javier. Gnuastro 0.14 [will be released next Monday](https://lists.gnu.org/archive/html/info-gnuastro/2021-01/msg00000.html) and usually gets built automatically in Conda Forge in an hour or two after the upload. So from early next week, `astquery` will be available as part of Gnuastro 0.14 in Conda Forge :smiley:.

**Comment by mohammad-akhlaghi** [comment]
Gnuastro 0.14 (containing `astquery`) has been successfully built on Conda-forge and [merged into the main branch](https://github.com/conda-forge/gnuastro-feedstock/pull/7) :smiley:. So, I am closing this issue :wink:.
